import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./global.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className={`${rubik.className} bg-veryLightGray`}>{children}</body>
    </html>
  );
}
